name: Matrix Demo
on: push
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [12, 14, 16]
                operation-system: [ubuntu-latest, windows-latest]
                include:
                    - node-version: 18
                      operation-system: ubuntu-latest
                exclude:
                    - node-version: 12
                      operation-system: windows-latest
        runs-on: ${{ matrix.operation-system }}
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: npm ci
            - name: Build project
              run: npm run build